language: ruby
cache:
  bundler: true
rvm:
  - 2.3.0
before_install:
  - gem install bundler -v 1.11.2

addons:
  postgresql: 9.5

env:
  global:
    - LOGIDZE_DB_USER=postgres
    - LOGIDZE_DB_NAME=logidze

before_script:
  - bundle exec rake dummy:db:create
  - bundle exec rake dummy:db:test:prepare
